## Netlify build settings
##[build]
##  publish = "_site"
##  command = "eleventy"
[dev]
  targetPort = 2024

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [".cache"] # Remote Asset Cache

[[plugins]]
package = "netlify-plugin-debug-cache"

## Cache control for CSS files
[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000'''

## Special page redirects
### Designs aliases
[[redirects]]
  from = "/design/"
  to = "/designs/"
[[redirects]]
  from = "/shirts/"
  to = "/designs/"
[[redirects]]
  from = "/posters/"
  to = "/designs/"
[[redirects]]
  from = "/art/"
  to = "/designs/"
[[redirects]]
  from = "/shop/"
  to = "/designs/"
[[redirects]]
  from = "/merch/"
  to = "/designs/"
### Other aliases
[[redirects]]
  from = "/thanks/"
  to = "/colophon/"
[[redirects]]
  from = "/follow/"
  to = "/rss.xml"
  status = 301
  force = true
[[redirects]]
  from = "/resume/"
  to = "/about/#resume"
### Well-known
[[redirects]]
  from = "/.well-known/avatar"
  to = "/assets/img/profile.jpg"
  status = 200
[[redirects]]
  from = "/.well-known/pronouns"
  to = "/.well-known/pronouns.txt"
  status = 200

## Legacy URL redirects
[[redirects]]
  from = "/projects/state-of-html-2023/"
  to = "/projects/devographics-surveys/"
  status = 301
[[redirects]]
  from = "/projects/state-of-js-2021/"
  to = "/projects/devographics-surveys/"
  status = 301
[[redirects]]
  from = "/projects/state-of-css-2021/"
  to = "/projects/devographics-surveys/"
  status = 301
[[redirects]]
  from = "/acknowledgements/"
  to = "/colophon/"
  status = 301
[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 303
[[redirects]]
  from = "/da/*"
  to = "/da/index.html"
  status = 303

## Miscellaneous
[[redirects]]
  from = "/blog/slider-fitting-the-tallest-element-in-pure-css/*"
  to = "/blog/vertical-slider-fitting-the-tallest-element-in-pure-css/:splat"
  status = 301

## Error 404 redirect
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404